ALTER TABLE products
MODIFY COLUMN product_name VARCHAR(300) NOT NULL,
MODIFY COLUMN price NUMERIC(10, 2) CHECK (price > 0) NOT NULL,
MODIFY COLUMN description TEXT NOT NULL,
MODIFY COLUMN amount_in_stock INT NOT NULL CHECK (amount_in_stock > 0),
MODIFY COLUMN image VARCHAR(300) NOT NULL;